baseurl = "https://xiaming.com.cn"
languageCode = "en-us"
theme = "xiamingcomcn"
paginate = 5

[params]
  # dir name of your blog content (default is `content/posts`)
  contentTypeName = "posts"
  # "light" or "dark"
  defaultTheme = "light"
  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 5
  # Enable to show reading time in minutes for posts
  showReadingTime = false

[permalinks]
  posts = "/:filename/"

[languages]
  [languages.en]
    title = "夏明"
    subtitle = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    writtenBy = "Written by"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "min read"
    dateFormatSingle = "2006-01-02"
    dateFormatList = "2006-01-02"

    [languages.en.params.logo]
      logoText = "夏明"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "archive"
        name = "归档"
        url = "/archive"
		weight="1"
      [[languages.en.menu.main]]
        identifier = "album"
        name = "相册"
        url = "#"
        weight="2"
      [[languages.en.menu.main]]
        identifier = "project"
        name = "项目"
        url = "#"
        weight="3"
      [[languages.en.menu.main]]
        identifier = "links"
        name = "友链"
        url = "/links"
        weight="4"
      [[languages.en.menu.main]]
        identifier = "about"
        name = "关于"
        url = "/about"
        weight="5"
